# Generated by Django 3.2.3 on 2021-07-28 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_bin',
            fields=[
                ('bin_id', models.AutoField(primary_key=True, serialize=False)),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Add_buildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('area', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('identifier', models.CharField(max_length=30)),
                ('height', models.IntegerField()),
                ('structure', models.CharField(max_length=30)),
                ('flooring', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Add_employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('ssn', models.IntegerField()),
                ('tin', models.IntegerField()),
                ('employee_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Add_products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('brand', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=25)),
                ('quantity', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('length', models.IntegerField()),
                ('Width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Add_racks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_name', models.CharField(max_length=30)),
                ('weight', models.IntegerField()),
                ('nof_bins', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('length', models.IntegerField()),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.add_buildings')),
            ],
        ),
        migrations.CreateModel(
            name='Add_supervisor',
            fields=[
                ('supervisor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
                ('ssn', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Add_rows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('weight', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('length', models.IntegerField()),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.add_buildings')),
                ('rack_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.add_racks')),
            ],
        ),
        migrations.CreateModel(
            name='Add_box',
            fields=[
                ('box_id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.IntegerField()),
                ('bin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.add_bin')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.add_products')),
            ],
        ),
        migrations.AddField(
            model_name='add_bin',
            name='rack_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.add_racks'),
        ),
    ]
